name: Build APK

on:
  workflow_dispatch: # Permite executar manualmente
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew sample:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: sample-debug.apk
          path: sample/build/outputs/apk/debug/sample-debug.apk
